// Auto generated by utensor-cli

#include "data_weight.hpp"
#include "uTensor/ops/MathOps.hpp"
#include "data.hpp"
#include "uTensor/ops/NnOps.hpp"
#include "uTensor/ops/ArrayOps.hpp"
#include "uTensor/ops/MatrixOps.hpp"
#include "uTensor/core/context.hpp"
#include "uTensor/core/tensor.hpp"


void get_data_ctx(Context& ctx, Tensor* input_0) {

{ // add tensor for placeholders
    ctx.add(input_0, "dense_1_input_1:0", 2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_1_MatMul_eightbit_dense_1_input_1__port__0_reshape_dims_0), 
            "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_1_input_1:0", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reshape_dims:0" },
             { "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_1_MatMul_eightbit_dense_1_input_1__port__0_reduction_dims_0), 
            "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reshape:0", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reduction_dims:0" },
             { "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reshape:0", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/reduction_dims:0" },
             { "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_1_input_1:0",  "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/min:0", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/max:0" },
             {  "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:0",  "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:1", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({10,12}, inline_dense_1_1_kernel_0), 
            "dense_1_1/kernel:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_1_MatMul_eightbit_dense_1_1_MatMul_ReadVariableOp__port__0_reshape_dims_0), 
            "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_1_1/kernel:0", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reshape_dims:0" },
             { "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_1_MatMul_eightbit_dense_1_1_MatMul_ReadVariableOp__port__0_reduction_dims_0), 
            "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reshape:0", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reshape:0", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_1_1/kernel:0",  "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/min:0", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/max:0" },
             {  "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:0",  "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:1", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_1_1/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:0", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:1", "dense_1_1/MatMul_eightbit/dense_1_input_1__port__0/quantize:2", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:0", "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:1",  "dense_1_1/MatMul_eightbit/dense_1_1/MatMul/ReadVariableOp__port__0/quantize:2" },
             { "dense_1_1/MatMul/eightbit:0", "dense_1_1/MatMul/eightbit:1",  "dense_1_1/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_1_1/MatMul/eightbit:0", "dense_1_1/MatMul/eightbit:1", "dense_1_1/MatMul/eightbit:2" },
             { "dense_1_1/MatMul/eightbit/requant_range:0", "dense_1_1/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_1_1/MatMul/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/MatMul/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_1_1/MatMul/eightbit:0", "dense_1_1/MatMul/eightbit:1", "dense_1_1/MatMul/eightbit:2", "dense_1_1/MatMul/eightbit/requant_range:0", "dense_1_1/MatMul/eightbit/requant_range:1" },
             { "dense_1_1/MatMul/eightbit/requantize:0", "dense_1_1/MatMul/eightbit/requantize:1", "dense_1_1/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({12}, inline_dense_1_1_bias_0), 
            "dense_1_1/bias:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_1_BiasAdd_eightbit_dense_1_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0), 
            "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_1_1/bias:0", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reshape_dims:0" },
             { "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_1_BiasAdd_eightbit_dense_1_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0), 
            "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reshape:0", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reshape:0", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_1_1/bias:0",  "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/min:0", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/max:0" },
             {  "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:0",  "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:1", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_1_1/BiasAdd/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "dense_1_1/MatMul/eightbit/requantize:0", "dense_1_1/MatMul/eightbit/requantize:1", "dense_1_1/MatMul/eightbit/requantize:2", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:0", "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:1",  "dense_1_1/BiasAdd_eightbit/dense_1_1/BiasAdd/ReadVariableOp__port__0/quantize:2" },
             { "dense_1_1/BiasAdd/eightbit:0", "dense_1_1/BiasAdd/eightbit:1",  "dense_1_1/BiasAdd/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_1_1/BiasAdd/eightbit:0", "dense_1_1/BiasAdd/eightbit:1", "dense_1_1/BiasAdd/eightbit:2" },
             { "dense_1_1/BiasAdd/eightbit/requant_range:0", "dense_1_1/BiasAdd/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_1_1/BiasAdd/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/BiasAdd/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_1_1/BiasAdd/eightbit:0", "dense_1_1/BiasAdd/eightbit:1", "dense_1_1/BiasAdd/eightbit:2", "dense_1_1/BiasAdd/eightbit/requant_range:0", "dense_1_1/BiasAdd/eightbit/requant_range:1" },
             { "dense_1_1/BiasAdd/eightbit/requantize:0", "dense_1_1/BiasAdd/eightbit/requantize:1", "dense_1_1/BiasAdd/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1_1/Relu/eightbit:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/Relu/eightbit:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1_1/Relu/eightbit:2", 1);
    ctx.push(new QuantizedReluOp<uint8_t, float, uint8_t>(), 
             { "dense_1_1/BiasAdd/eightbit/requantize:0", "dense_1_1/BiasAdd/eightbit/requantize:1", "dense_1_1/BiasAdd/eightbit/requantize:2" },
             { "dense_1_1/Relu/eightbit:0", "dense_1_1/Relu/eightbit:1", "dense_1_1/Relu/eightbit:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({12,8}, inline_dense_2_1_kernel_0), 
            "dense_2_1/kernel:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_1_MatMul_eightbit_dense_2_1_MatMul_ReadVariableOp__port__0_reshape_dims_0), 
            "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_2_1/kernel:0", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reshape_dims:0" },
             { "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_1_MatMul_eightbit_dense_2_1_MatMul_ReadVariableOp__port__0_reduction_dims_0), 
            "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reshape:0", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reshape:0", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_2_1/kernel:0",  "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/min:0", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/max:0" },
             {  "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:0",  "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:1", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_2_1/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "dense_1_1/Relu/eightbit:0", "dense_1_1/Relu/eightbit:1", "dense_1_1/Relu/eightbit:2", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:0", "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:1",  "dense_2_1/MatMul_eightbit/dense_2_1/MatMul/ReadVariableOp__port__0/quantize:2" },
             { "dense_2_1/MatMul/eightbit:0", "dense_2_1/MatMul/eightbit:1",  "dense_2_1/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_2_1/MatMul/eightbit:0", "dense_2_1/MatMul/eightbit:1", "dense_2_1/MatMul/eightbit:2" },
             { "dense_2_1/MatMul/eightbit/requant_range:0", "dense_2_1/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_2_1/MatMul/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/MatMul/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_2_1/MatMul/eightbit:0", "dense_2_1/MatMul/eightbit:1", "dense_2_1/MatMul/eightbit:2", "dense_2_1/MatMul/eightbit/requant_range:0", "dense_2_1/MatMul/eightbit/requant_range:1" },
             { "dense_2_1/MatMul/eightbit/requantize:0", "dense_2_1/MatMul/eightbit/requantize:1", "dense_2_1/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({8}, inline_dense_2_1_bias_0), 
            "dense_2_1/bias:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_1_BiasAdd_eightbit_dense_2_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0), 
            "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_2_1/bias:0", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reshape_dims:0" },
             { "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_1_BiasAdd_eightbit_dense_2_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0), 
            "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reshape:0", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reshape:0", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_2_1/bias:0",  "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/min:0", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/max:0" },
             {  "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:0",  "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:1", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_2_1/BiasAdd/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "dense_2_1/MatMul/eightbit/requantize:0", "dense_2_1/MatMul/eightbit/requantize:1", "dense_2_1/MatMul/eightbit/requantize:2", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:0", "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:1",  "dense_2_1/BiasAdd_eightbit/dense_2_1/BiasAdd/ReadVariableOp__port__0/quantize:2" },
             { "dense_2_1/BiasAdd/eightbit:0", "dense_2_1/BiasAdd/eightbit:1",  "dense_2_1/BiasAdd/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_2_1/BiasAdd/eightbit:0", "dense_2_1/BiasAdd/eightbit:1", "dense_2_1/BiasAdd/eightbit:2" },
             { "dense_2_1/BiasAdd/eightbit/requant_range:0", "dense_2_1/BiasAdd/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_2_1/BiasAdd/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/BiasAdd/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_2_1/BiasAdd/eightbit:0", "dense_2_1/BiasAdd/eightbit:1", "dense_2_1/BiasAdd/eightbit:2", "dense_2_1/BiasAdd/eightbit/requant_range:0", "dense_2_1/BiasAdd/eightbit/requant_range:1" },
             { "dense_2_1/BiasAdd/eightbit/requantize:0", "dense_2_1/BiasAdd/eightbit/requantize:1", "dense_2_1/BiasAdd/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_2_1/Relu/eightbit:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/Relu/eightbit:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2_1/Relu/eightbit:2", 1);
    ctx.push(new QuantizedReluOp<uint8_t, float, uint8_t>(), 
             { "dense_2_1/BiasAdd/eightbit/requantize:0", "dense_2_1/BiasAdd/eightbit/requantize:1", "dense_2_1/BiasAdd/eightbit/requantize:2" },
             { "dense_2_1/Relu/eightbit:0", "dense_2_1/Relu/eightbit:1", "dense_2_1/Relu/eightbit:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({8,1}, inline_dense_3_1_kernel_0), 
            "dense_3_1/kernel:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_3_1_MatMul_eightbit_dense_3_1_MatMul_ReadVariableOp__port__0_reshape_dims_0), 
            "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_3_1/kernel:0", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reshape_dims:0" },
             { "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_3_1_MatMul_eightbit_dense_3_1_MatMul_ReadVariableOp__port__0_reduction_dims_0), 
            "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reshape:0", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reshape:0", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_3_1/kernel:0",  "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/min:0", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/max:0" },
             {  "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:0",  "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:1", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_3_1/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "dense_2_1/Relu/eightbit:0", "dense_2_1/Relu/eightbit:1", "dense_2_1/Relu/eightbit:2", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:0", "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:1",  "dense_3_1/MatMul_eightbit/dense_3_1/MatMul/ReadVariableOp__port__0/quantize:2" },
             { "dense_3_1/MatMul/eightbit:0", "dense_3_1/MatMul/eightbit:1",  "dense_3_1/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_3_1/MatMul/eightbit:0", "dense_3_1/MatMul/eightbit:1", "dense_3_1/MatMul/eightbit:2" },
             { "dense_3_1/MatMul/eightbit/requant_range:0", "dense_3_1/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_3_1/MatMul/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/MatMul/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_3_1/MatMul/eightbit:0", "dense_3_1/MatMul/eightbit:1", "dense_3_1/MatMul/eightbit:2", "dense_3_1/MatMul/eightbit/requant_range:0", "dense_3_1/MatMul/eightbit/requant_range:1" },
             { "dense_3_1/MatMul/eightbit/requantize:0", "dense_3_1/MatMul/eightbit/requantize:1", "dense_3_1/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({1}, inline_dense_3_1_bias_0), 
            "dense_3_1/bias:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_3_1_BiasAdd_eightbit_dense_3_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0), 
            "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_3_1/bias:0", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reshape_dims:0" },
             { "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_3_1_BiasAdd_eightbit_dense_3_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0), 
            "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reshape:0", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reshape:0", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/reduction_dims:0" },
             { "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_3_1/bias:0",  "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/min:0", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/max:0" },
             {  "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:0",  "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:1", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_3_1/BiasAdd/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "dense_3_1/MatMul/eightbit/requantize:0", "dense_3_1/MatMul/eightbit/requantize:1", "dense_3_1/MatMul/eightbit/requantize:2", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:0", "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:1",  "dense_3_1/BiasAdd_eightbit/dense_3_1/BiasAdd/ReadVariableOp__port__0/quantize:2" },
             { "dense_3_1/BiasAdd/eightbit:0", "dense_3_1/BiasAdd/eightbit:1",  "dense_3_1/BiasAdd/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_3_1/BiasAdd/eightbit:0", "dense_3_1/BiasAdd/eightbit:1", "dense_3_1/BiasAdd/eightbit:2" },
             { "dense_3_1/BiasAdd/eightbit/requant_range:0", "dense_3_1/BiasAdd/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_3_1/BiasAdd/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_3_1/BiasAdd/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_3_1/BiasAdd/eightbit:0", "dense_3_1/BiasAdd/eightbit:1", "dense_3_1/BiasAdd/eightbit:2", "dense_3_1/BiasAdd/eightbit/requant_range:0", "dense_3_1/BiasAdd/eightbit/requant_range:1" },
             { "dense_3_1/BiasAdd/eightbit/requantize:0", "dense_3_1/BiasAdd/eightbit/requantize:1", "dense_3_1/BiasAdd/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>(), "dense_3_1/BiasAdd:0");
    ctx.push(new DequantizeOp(), 
             { "dense_3_1/BiasAdd/eightbit/requantize:0", "dense_3_1/BiasAdd/eightbit/requantize:1", "dense_3_1/BiasAdd/eightbit/requantize:2" },
             { "dense_3_1/BiasAdd:0" });
}
}