// Auto generated by utensor-cli

#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_input_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_input_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_1_1_kernel_0 [ 120 ] = {  0.037096124,  0.19660532,  -0.18589512,  -0.048333094,  0.0819922,  -0.12498714,  -0.6293509,  -0.00032150745,  -0.38583916,  -0.400948,  -0.013787627,  -0.37384564,  0.10695001,  -0.36677906,  0.03674817,  0.41820815,  -0.050094668,  -0.06009176,  -0.49332538,  0.0713318,  0.06342417,  -0.08568993,  0.16648513,  -0.16705075,  -0.093364455,  -0.051507056,  -0.005317807,  0.1922662,  0.016311198,  0.13651001,  0.12621108,  0.2219075,  -0.04187846,  0.16487318,  -0.14099443,  -0.45281225,  -0.58562964,  -0.11927527,  -0.24177322,  -0.16140392,  0.116741255,  -0.10789707,  -0.21418881,  0.24326646,  -0.1826058,  -0.4471599,  -0.38154656,  0.23007065,  0.16749316,  -0.081347376,  -0.14963168,  -0.08362863,  -0.30652934,  0.070102446,  0.20661026,  -0.22648612,  -0.22433311,  0.29135036,  -0.09421912,  -0.12008533,  0.16221927,  -0.194976,  0.022137403,  0.36455888,  -0.20052107,  0.4678483,  -0.3272458,  0.23033744,  0.4102714,  -0.3777317,  -0.25842094,  0.13991404,  -0.06975665,  0.068698406,  -0.39197764,  -0.25290668,  0.4608373,  0.008253503,  0.20534365,  -0.24717945,  -0.22286674,  -0.062870234,  0.22515273,  0.020469189,  -0.08897145,  -0.46970654,  0.30231535,  0.6353514,  0.40114892,  -0.459404,  0.28017768,  -0.20741293,  -0.40007117,  0.5113382,  0.24800342,  -0.08818498,  0.33258504,  0.29616207,  -0.47887495,  0.45213714,  -0.24443394,  -0.1573917,  0.58292717,  -0.089829266,  -0.51574546,  0.23461115,  0.044094086,  0.1635012,  0.029954929,  -0.13887078,  0.06274372,  0.7090012,  0.819173,  0.12443124,  0.7691846,  -0.21700853,  0.47150344,  -0.19882908,  -0.041316777,  0.47784787,  };
#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_1_1_bias_0 [ 12 ] = {  -0.1457798,  0.0,  0.0,  -0.008825,  -0.06528557,  -0.03006679,  -0.11449085,  0.0,  0.0,  0.0,  0.0,  0.0,  };
#include <stdint.h>

const int inline_dense_1_1_BiasAdd_eightbit_dense_1_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_1_BiasAdd_eightbit_dense_1_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_2_1_kernel_0 [ 96 ] = {  0.18743241,  -0.14786652,  0.42590415,  -0.49300894,  -0.5199612,  0.000749391,  0.16571039,  -0.30712017,  -0.4116977,  0.4476785,  0.13495606,  0.38070595,  -0.16811815,  -0.5323667,  -0.41471216,  0.49056184,  -0.43843648,  0.038257778,  0.0280931,  0.17541277,  -0.52765286,  0.4141611,  0.50288963,  0.50666845,  -0.50431,  0.09284275,  -0.2511686,  0.00858974,  0.14443308,  0.45548037,  -0.16047421,  0.29029784,  -0.4659909,  0.015462026,  -0.19548962,  0.17006058,  -0.23666322,  0.26359856,  -0.49217325,  -0.508055,  -0.31586087,  0.51019955,  -0.21081626,  -0.23441023,  0.39576626,  0.027863147,  -0.20102444,  -0.376653,  -0.32226318,  -0.60499185,  -0.44951248,  -0.4897839,  -0.2868915,  0.20735808,  -0.48390082,  -0.24072863,  -0.042230844,  -0.22357097,  -0.32982355,  -0.54122704,  0.12013048,  -0.53946817,  0.15280312,  0.53246593,  -0.076996714,  -0.26010445,  -0.39811963,  0.46872973,  0.4156605,  -0.38794518,  -0.04505533,  -0.019918323,  -0.113348424,  0.3485462,  0.09153485,  0.21479326,  -0.21512511,  0.09499675,  -0.43837327,  0.32111257,  -0.5030543,  -0.3023954,  -0.38978124,  -0.50547826,  -0.063151866,  -0.450833,  -0.4208508,  -0.15039498,  0.044359207,  0.545004,  0.07590699,  0.21470094,  -0.46099266,  -0.25307545,  -0.31362575,  0.3284188,  };
#include <stdint.h>

const int inline_dense_2_1_MatMul_eightbit_dense_2_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_2_1_MatMul_eightbit_dense_2_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_2_1_bias_0 [ 8 ] = {  0.0,  -0.10869347,  0.0,  -0.13043013,  -0.25786814,  0.050917614,  0.0,  -0.1177688,  };
#include <stdint.h>

const int inline_dense_2_1_BiasAdd_eightbit_dense_2_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_2_1_BiasAdd_eightbit_dense_2_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_3_1_kernel_0 [ 8 ] = {  -0.27390796,  -0.20787233,  -0.25423247,  -0.0065350565,  0.020496683,  0.7095595,  0.42389166,  -0.6292558,  };
#include <stdint.h>

const int inline_dense_3_1_MatMul_eightbit_dense_3_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_3_1_MatMul_eightbit_dense_3_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_3_1_bias_0 [ 1 ] = {  0.07384893,  };
#include <stdint.h>

const int inline_dense_3_1_BiasAdd_eightbit_dense_3_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_3_1_BiasAdd_eightbit_dense_3_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
