// Auto generated by utensor-cli

#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_input_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_input_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_1_1_kernel_0 [ 120 ] = {  0.058069482,  0.19660532,  -0.18589512,  -0.057398822,  0.08816564,  -0.12491787,  -0.61024714,  -0.00032150745,  -0.38583916,  -0.400948,  -0.013787627,  -0.37384564,  0.12621339,  -0.36677906,  0.03674817,  0.40900835,  -0.044029694,  -0.060022514,  -0.4744689,  0.0713318,  0.06342417,  -0.08568993,  0.16648513,  -0.16705075,  -0.07638304,  -0.051507056,  -0.005317807,  0.18175784,  0.021066014,  0.13657925,  0.14345372,  0.2219075,  -0.04187846,  0.16487318,  -0.14099443,  -0.45281225,  -0.5684203,  -0.11927527,  -0.24177322,  -0.1720358,  0.12139406,  -0.10782782,  -0.19712596,  0.24326646,  -0.1826058,  -0.4471599,  -0.38154656,  0.23007065,  0.18313107,  -0.081347376,  -0.14963168,  -0.09536018,  -0.30297962,  0.070171654,  0.2224173,  -0.22648612,  -0.22433311,  0.29135036,  -0.09421912,  -0.12008533,  0.17825489,  -0.194976,  0.022137403,  0.3536851,  -0.19612685,  0.4679177,  -0.31038,  0.23033744,  0.4102714,  -0.3777317,  -0.25842094,  0.13991404,  -0.053820003,  0.068698406,  -0.39197764,  -0.26405817,  0.46490642,  0.008322729,  0.22186148,  -0.24717945,  -0.22286674,  -0.062870234,  0.22515273,  0.020469189,  -0.07205441,  -0.46970654,  0.30231535,  0.6246447,  0.40563902,  -0.4593347,  0.29715583,  -0.20741293,  -0.40007117,  0.5113382,  0.24800342,  -0.08818498,  0.35130936,  0.29616207,  -0.47887495,  0.4396758,  -0.24184276,  -0.15732244,  0.5980996,  -0.089829266,  -0.51574546,  0.23461115,  0.044094086,  0.1635012,  0.052461196,  -0.13887078,  0.06274372,  0.6962567,  0.8213169,  0.12450055,  0.78413004,  -0.21700853,  0.47150344,  -0.19882908,  -0.041316777,  0.47784787,  };
#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_1_MatMul_eightbit_dense_1_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_1_1_bias_0 [ 12 ] = {  -0.12949142,  0.0,  0.0,  -0.019494133,  -0.060768984,  -0.02999752,  -0.095850736,  0.0,  0.0,  0.0,  0.0,  0.0,  };
#include <stdint.h>

const int inline_dense_1_1_BiasAdd_eightbit_dense_1_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_1_BiasAdd_eightbit_dense_1_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_2_1_kernel_0 [ 96 ] = {  0.18743241,  -0.073207065,  0.42590415,  -0.45441735,  -0.46495292,  0.02413988,  0.16571039,  -0.26967868,  -0.4116977,  0.4476785,  0.13495606,  0.38070595,  -0.16811815,  -0.5323667,  -0.41471216,  0.49056184,  -0.43843648,  0.038257778,  0.0280931,  0.17541277,  -0.52765286,  0.4141611,  0.50288963,  0.50666845,  -0.50431,  0.13097861,  -0.2511686,  0.047396053,  0.19948056,  0.45603725,  -0.16047421,  0.32777673,  -0.4659909,  0.05452407,  -0.19548962,  0.20859776,  -0.18155374,  0.26698527,  -0.49217325,  -0.47054657,  -0.31586087,  0.51022494,  -0.21081626,  -0.23441023,  0.39579058,  0.027837371,  -0.20102444,  -0.37660095,  -0.32226318,  -0.6246652,  -0.44951248,  -0.4499368,  -0.23216486,  0.19658825,  -0.48390082,  -0.20276627,  -0.042230844,  -0.22357097,  -0.32982355,  -0.54122704,  0.12013048,  -0.53946817,  0.15280312,  0.53246593,  -0.076996714,  -0.26010445,  -0.39811963,  0.46872973,  0.4156605,  -0.38794518,  -0.04505533,  -0.019918323,  -0.113348424,  0.3485462,  0.09153485,  0.21479326,  -0.21512511,  0.09499675,  -0.43837327,  0.32111257,  -0.5030543,  -0.3023954,  -0.38978124,  -0.50547826,  -0.063151866,  -0.450833,  -0.4208508,  -0.15039498,  0.044359207,  0.545004,  0.07590699,  0.21470094,  -0.46099266,  -0.25307545,  -0.31362575,  0.3284188,  };
#include <stdint.h>

const int inline_dense_2_1_MatMul_eightbit_dense_2_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_2_1_MatMul_eightbit_dense_2_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_2_1_bias_0 [ 8 ] = {  0.0,  -0.06543493,  0.0,  -0.09218445,  -0.19751975,  0.050628077,  0.0,  -0.08054508,  };
#include <stdint.h>

const int inline_dense_2_1_BiasAdd_eightbit_dense_2_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_2_1_BiasAdd_eightbit_dense_2_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_3_1_kernel_0 [ 8 ] = {  -0.27390796,  -0.0043750126,  -0.25423247,  0.012291448,  0.012782529,  0.71026605,  0.42389166,  -0.66352534,  };
#include <stdint.h>

const int inline_dense_3_1_MatMul_eightbit_dense_3_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_3_1_MatMul_eightbit_dense_3_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_3_1_bias_0 [ 1 ] = {  0.07294002,  };
#include <stdint.h>

const int inline_dense_3_1_BiasAdd_eightbit_dense_3_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_3_1_BiasAdd_eightbit_dense_3_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
