// Auto generated by utensor-cli

#ifndef __MODELS_DATA_H5_H
#define __MODELS_DATA_H5_H
#include "uTensor/core/context.hpp"
void get_data_h5_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_DATA_H5_H