// Auto generated by utensor-cli

#include <stdint.h>

const int inline_dense_1_MatMul_eightbit_dense_1_input__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_MatMul_eightbit_dense_1_input__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_1_kernel_0 [ 120 ] = {  0.03828902,  0.19660532,  -0.18589512,  -0.05768587,  0.08825397,  -0.12506165,  -0.6123478,  -0.00032150745,  -0.38583916,  -0.400948,  -0.013787627,  -0.37384564,  0.110176526,  -0.36677906,  0.03674817,  0.4119816,  -0.040699176,  -0.06016632,  -0.4736789,  0.0713318,  0.06342417,  -0.08568993,  0.16648513,  -0.16705075,  -0.09103693,  -0.051507056,  -0.005317807,  0.18605855,  0.025772383,  0.13643526,  0.14348541,  0.2219075,  -0.04187846,  0.16487318,  -0.14099443,  -0.45281225,  -0.58719647,  -0.11927527,  -0.24177322,  -0.17125446,  0.12240528,  -0.10797269,  -0.20383039,  0.24326646,  -0.1826058,  -0.4471599,  -0.38154656,  0.23007065,  0.16673413,  -0.081347376,  -0.14963168,  -0.09213975,  -0.29952046,  0.07002091,  0.21554841,  -0.22648612,  -0.22433311,  0.29135036,  -0.09421912,  -0.12008533,  0.16191508,  -0.194976,  0.022137403,  0.35694072,  -0.19263202,  0.46776554,  -0.3199,  0.23033744,  0.4102714,  -0.3777317,  -0.25842094,  0.13991404,  -0.068918504,  0.068698406,  -0.39197764,  -0.2592334,  0.47001073,  0.0081716785,  0.21043994,  -0.24717945,  -0.22286674,  -0.062870234,  0.22515273,  0.020469189,  -0.087615095,  -0.46970654,  0.30231535,  0.62942415,  0.41070232,  -0.45948046,  0.28224483,  -0.20741293,  -0.40007117,  0.5113382,  0.24800342,  -0.08818498,  0.33576876,  0.29616207,  -0.47887495,  0.44627246,  -0.23485404,  -0.1574685,  0.5803015,  -0.089829266,  -0.51574546,  0.23461115,  0.044094086,  0.1635012,  0.03482769,  -0.13887078,  0.06274372,  0.7026131,  0.82819104,  0.12435472,  0.76207197,  -0.21700853,  0.47150344,  -0.19882908,  -0.041316777,  0.47784787,  };
#include <stdint.h>

const int inline_dense_1_MatMul_eightbit_dense_1_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_MatMul_eightbit_dense_1_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_1_bias_0 [ 12 ] = {  -0.14392456,  0.0,  0.0,  -0.015160293,  -0.0560091,  -0.030102089,  -0.09908503,  0.0,  0.0,  0.0,  0.0,  0.0,  };
#include <stdint.h>

const int inline_dense_1_BiasAdd_eightbit_dense_1_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_1_BiasAdd_eightbit_dense_1_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_2_kernel_0 [ 96 ] = {  0.18743241,  -0.09570137,  0.42590415,  -0.49163288,  -0.4902791,  0.001674453,  0.16571039,  -0.31190306,  -0.4116977,  0.4476785,  0.13495606,  0.38070595,  -0.16811815,  -0.5323667,  -0.41471216,  0.49056184,  -0.43843648,  0.038257778,  0.0280931,  0.17541277,  -0.52765286,  0.4141611,  0.50288963,  0.50666845,  -0.50431,  0.118926354,  -0.2511686,  0.008081,  0.17337376,  0.45473966,  -0.16047421,  0.28573886,  -0.4659909,  0.043718025,  -0.19548962,  0.17005076,  -0.208149,  0.26302642,  -0.49217325,  -0.5125076,  -0.31586087,  0.51011807,  -0.21081626,  -0.23441023,  0.3956867,  0.02794493,  -0.20102444,  -0.3766529,  -0.32226318,  -0.6150434,  -0.44951248,  -0.47711882,  -0.26189,  0.20424794,  -0.48390082,  -0.24409996,  -0.042230844,  -0.22357097,  -0.32982355,  -0.54122704,  0.12013048,  -0.53946817,  0.15280312,  0.53246593,  -0.076996714,  -0.26010445,  -0.39811963,  0.46872973,  0.4156605,  -0.38794518,  -0.04505533,  -0.019918323,  -0.113348424,  0.3485462,  0.09153485,  0.21479326,  -0.21512511,  0.09499675,  -0.43837327,  0.32111257,  -0.5030543,  -0.3023954,  -0.38978124,  -0.50547826,  -0.063151866,  -0.450833,  -0.4208508,  -0.15039498,  0.044359207,  0.545004,  0.07590699,  0.21470094,  -0.46099266,  -0.25307545,  -0.31362575,  0.3284188,  };
#include <stdint.h>

const int inline_dense_2_MatMul_eightbit_dense_2_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_2_MatMul_eightbit_dense_2_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_2_bias_0 [ 8 ] = {  0.0,  -0.07387769,  0.0,  -0.13249236,  -0.23415223,  0.05129333,  0.0,  -0.12261917,  };
#include <stdint.h>

const int inline_dense_2_BiasAdd_eightbit_dense_2_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_2_BiasAdd_eightbit_dense_2_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_3_kernel_0 [ 8 ] = {  -0.27390796,  -0.066999115,  -0.25423247,  -0.01230623,  -0.017401338,  0.7077097,  0.42389166,  -0.6348839,  };
#include <stdint.h>

const int inline_dense_3_MatMul_eightbit_dense_3_MatMul_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_3_MatMul_eightbit_dense_3_MatMul_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_dense_3_bias_0 [ 1 ] = {  0.074620016,  };
#include <stdint.h>

const int inline_dense_3_BiasAdd_eightbit_dense_3_BiasAdd_ReadVariableOp__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_dense_3_BiasAdd_eightbit_dense_3_BiasAdd_ReadVariableOp__port__0_reduction_dims_0 [ 1 ] = {  0,  };
